
const dict = {
  fr: {
    top:"Traduction de documents • Délai habituel : 24 à 48 h",
    range:"Les devis se situent généralement entre 25 $ et 50 $ par document",
    serv:"Services", how:"Fonctionnement", pricing:"Tarifs", quote:"Obtenir un devis",
    ey:"Traduction professionnelle de documents",
    title:"Vos mots,<br><em>bien compris.</em>",
    hero:"Envoyez-nous votre document et indiquez-nous la langue souhaitée. Nous traduisons entre l’anglais, l’espagnol, le français et le créole haïtien, puis nous livrons le fichier final par e-mail.",
    upload:"Envoyer votre document", see:"Voir le fonctionnement", langs:"Langues", turn:"Délai habituel", range2:"Fourchette habituelle", emailWord:"E-mail", delivery:"Livraison numérique",
    langEnglish:"Anglais", langSpanish:"Espagnol", langFrench:"Français", langCreole:"Créole haïtien",
    explore:"Découvrir", exploreTitle:"Tout ce dont vous avez besoin, sans tout mettre sur une seule page.",
    homeServices:"Services", homeServicesP:"Découvrez les types de documents officiels et non officiels que nous traduisons.",
    homeHow:"Fonctionnement", homeHowP:"Envoyez le fichier, recevez le devis, payez et recevez votre traduction.",
    homePricing:"Tarifs", homePricingP:"Comprenez la fourchette habituelle de 25 $ à 50 $ et ce qui influence votre devis.",
    homeQuote:"Obtenir un devis", homeQuoteP:"Choisissez les langues et envoyez le document que vous souhaitez faire examiner.",
    homeFaq:"FAQ", homeFaqP:"Délais, documents officiels, paiements et questions fréquentes.",
    homeStart:"Commencer", homeStartP:"Prêt à traduire ? Envoyez votre document et nous l’examinerons d’abord.",
    what:"Ce que nous traduisons", serviceHero:"Des documents importants, traduits clairement.", serviceHeroP:"Nous prenons en charge les documents officiels et non officiels en anglais, espagnol, français et créole haïtien.",
    c1:"Documents d’état civil", c1p:"Actes de naissance et de mariage, pièces d’identité et autres documents personnels.",
    c2:"Scolaire et académique", c2p:"Relevés de notes, diplômes, lettres, attestations d’inscription et autres documents scolaires.",
    c3:"Entreprise et travail", c3p:"Lettres d’emploi, documents professionnels, formulaires, politiques et correspondance.",
    c4:"Documents personnels", c4p:"Lettres, déclarations, avis et autres documents non officiels.",
    c5:"Formulaires et dossiers", c5p:"Formulaires administratifs, dossiers et pièces justificatives.",
    c6:"Autre chose ?", c6p:"Envoyez-le. Nous examinerons d’abord le fichier pour confirmer si nous pouvons accepter le projet.",
    simple:"Simple du début à la fin", simple2:"Envoyez le fichier. Validez le devis. Recevez la traduction.", processIntro:"Aucune création de compte compliquée. Commencez avec votre document et nous vous guidons pour la suite.",
    p1:"Envoyer", p1p:"Choisissez la langue source et la langue cible, puis envoyez le document.",
    p2:"Examen et devis", p2p:"Nous examinons la longueur et la complexité puis envoyons le prix exact avant de commencer.",
    p3:"Payer", p3p:"Pour le moment, le paiement se fait par Zelle. Les détails sont confirmés avec votre devis.",
    p4:"Recevoir", p4p:"La traduction terminée est envoyée à l’adresse e-mail fournie.",
    clear:"Tarification simple", clear2:"Une fourchette claire d’abord. Un devis exact après examen du document.", pricingIntro:"La plupart des documents standards se situent dans la fourchette ci-dessous. Nous confirmons le montant exact avant le début du travail.",
    per:"fourchette habituelle par document", pc1:"Le prix final dépend de la longueur du document, de sa mise en page, de la combinaison linguistique et de sa complexité.", pc2:"Vous approuvez le devis avant le début de la traduction.", pc3:"Les documents volumineux, multipages ou spécialisés peuvent être facturés en dehors de la fourchette habituelle.",
    paymentLabel:"Paiement", zelleAccepted:"Zelle est accepté pour le moment.", zn:"N’envoyez aucun paiement avant confirmation de votre devis.",
    rq:"Demander un devis", rq2:"Dites-nous ce que vous souhaitez traduire.", rqp:"Remplissez le formulaire et sélectionnez votre document. Nous examinerons votre demande avant de confirmer le prix final.", z:"Paiement Zelle",
    email:"Votre e-mail", emailPh:"vous@exemple.com", from:"Traduire de", to:"Traduire vers", selectLang:"Choisir une langue", doc:"Votre document", choose:"Choisir un document", notes:"Quelque chose à préciser ? (facultatif)", notesPh:"Délai, demande de mise en page, nombre de pages, etc.", privacy:"N’envoyez que des documents que vous êtes autorisé à partager. Votre fichier ne doit être utilisé que pour préparer et exécuter votre demande de traduction.", agreeHtml:'J’accepte les <a href="terms.html" target="_blank">Conditions générales</a> et la <a href="privacy.html" target="_blank">Politique de confidentialité</a>.', prepare:"Préparer la demande de devis",
    faq:"Quelques informations à connaître avant d’envoyer votre document.", q1:"Combien de temps prend une traduction ?", a1:"La plupart des demandes standards visent un délai de 24 à 48 heures après confirmation du devis et du paiement. Les fichiers volumineux ou plus complexes peuvent demander davantage de temps.", q2:"Combien cela coûte-t-il ?", a2:"La plupart des documents standards se situent entre 25 $ et 50 $. Nous confirmons le prix exact après examen du fichier.", q3:"Quelles langues proposez-vous ?", a3:"Anglais, espagnol, français et créole haïtien.", q4:"Acceptez-vous les documents officiels ?", a4:"Oui, vous pouvez soumettre des documents officiels ou non officiels pour examen. Si l’organisme destinataire exige une certification, une notarisation, une qualification précise du traducteur ou un format particulier, indiquez-le avant le début du travail afin que l’exigence puisse être confirmée.", q5:"Comment payer ?", a5:"Zelle est actuellement accepté. Attendez la confirmation de votre devis final avant d’envoyer le paiement.",
    termsLink:"Conditions générales", privacyLink:"Politique de confidentialité", refundLink:"Remboursements et annulations", faqLink:"FAQ", foot:"Des mots clairs. Dans plusieurs langues.", fl:"Anglais • Espagnol • Français • Créole haïtien",
    legalLabel:"Mentions légales", effective:"En vigueur : 22 septembre 2026", termsTitle:"Conditions générales",
    termsIntro:"Ces conditions expliquent la gestion des demandes de devis, des paiements, du travail de traduction et de la livraison. En soumettant une demande ou en approuvant un devis, vous acceptez ces conditions.",
    termsH1:"1. Services", termsP1:"We Translate fournit des services de traduction de documents entre l’anglais, l’espagnol, le français et le créole haïtien. Nous pouvons accepter ou refuser une demande après examen du document, de la combinaison linguistique, des exigences de mise en page, du délai et de la complexité.",
    termsH2:"2. Devis et tarifs", termsP2:"Les prix affichés sur le site sont uniquement indicatifs. La plupart des documents standards devraient se situer dans la fourchette indiquée de 25 $ à 50 $, mais le prix final peut être supérieur ou inférieur selon la longueur, la complexité, la mise en page et les exigences particulières. Le travail de traduction commence uniquement après approbation du devis final et réception du paiement requis.",
    termsH3:"3. Délais", termsP3:"Le délai habituel affiché sur le site est de 24 à 48 heures pour les demandes standards après approbation du devis et paiement. Il s’agit d’une estimation et non d’une garantie. Les fichiers volumineux, scans de mauvaise qualité, sujets spécialisés ou révisions peuvent demander plus de temps.",
    termsH4:"4. Responsabilités du client", termsP4:"Vous êtes responsable de fournir des fichiers complets et lisibles, des instructions exactes et de confirmer la langue cible ainsi que l’usage prévu. Vous devez avoir le droit légal ou l’autorisation de partager chaque document soumis.",
    termsH5:"5. Documents officiels et acceptation", termsP5:"We Translate peut traduire des documents officiels et non officiels. Sauf confirmation écrite spécifique pour une commande donnée, nous ne garantissons pas qu’une traduction répondra aux exigences de certification, notarisation, utilisation devant un tribunal, dossier d’immigration, université, organisme public ou toute autre institution destinataire. Le client doit vérifier les exigences de l’institution avant de commander.",
    termsH6:"6. Paiements", termsP6:"Les paiements sont actuellement acceptés par Zelle après confirmation du devis final. N’envoyez aucun paiement avant cette confirmation. Les modalités de paiement peuvent être mises à jour.",
    termsH7:"7. Révisions", termsP7:"Si vous pensez qu’une traduction livrée contient une erreur, contactez-nous rapidement en indiquant précisément la partie concernée. Les corrections raisonnables d’erreurs de traduction peuvent être effectuées sans frais supplémentaires. Toute modification du document d’origine, ajout de contenu, nouvelle demande de mise en page ou changement d’instructions peut nécessiter un nouveau devis.",
    termsH8:"8. Annulations et remboursements", termsP8:'L’éligibilité à une annulation ou à un remboursement dépend de l’avancement du travail. Consultez notre <a href="refunds.html">Politique de remboursement et d’annulation</a> pour plus de détails.',
    termsH9:"9. Livraison des fichiers", termsP9:"Les traductions terminées sont généralement livrées par voie électronique à l’adresse e-mail fournie par le client. Le client est responsable de fournir une adresse e-mail valide et de vérifier les dossiers spam ou courrier indésirable.",
    termsH10:"10. Exactitude et limitations", termsP10:"Nous visons des traductions soignées et exactes. Toutefois, le client doit vérifier les noms, dates, chiffres et autres informations essentielles à la livraison. Dans la mesure permise par la loi, We Translate n’est pas responsable des pertes indirectes ou consécutives résultant de l’utilisation d’une traduction ou de la décision d’une institution de la refuser.",
    termsH11:"11. Soumissions interdites", termsP11:"Vous ne pouvez pas soumettre de contenu que vous n’êtes pas autorisé à partager, de contenu illégal, de logiciel malveillant ou de fichiers destinés à faciliter une fraude, une usurpation d’identité ou toute autre activité illégale.",
    termsH12:"12. Modification de ces conditions", termsP12:"Nous pouvons mettre à jour ces conditions à mesure que le service évolue. La date d’entrée en vigueur ci-dessus sera modifiée en cas de changement important.",
    termsH13:"13. Contact", termsP13:"Les questions concernant ces conditions peuvent être envoyées via le processus de devis/contact du site. Une adresse e-mail professionnelle dédiée pourra être ajoutée une fois confirmée.",
    privacyTitle:"Politique de confidentialité", privacyIntro:"Les demandes de traduction peuvent contenir des informations personnelles sensibles. Cette politique explique quelles informations sont concernées et comment elles doivent être traitées.",
    privacyH1:"1. Informations que vous fournissez", privacyP1:"Lors d’une demande de devis ou de traduction, vous pouvez fournir votre adresse e-mail, les langues source et cible, des notes et les documents que vous choisissez d’envoyer. Les documents soumis peuvent contenir des informations personnelles vous concernant ou concernant d’autres personnes.",
    privacyH2:"2. Utilisation des informations", privacyP2:"Les informations soumises via le site sont utilisées pour examiner votre demande, préparer un devis, effectuer la traduction, communiquer avec vous, livrer le travail terminé, traiter les demandes de service client liées et conserver les documents commerciaux nécessaires.",
    privacyH3:"3. Documents et informations sensibles", privacyP3:"N’envoyez que les documents nécessaires à la traduction et que vous êtes autorisé à partager. Évitez d’inclure des informations sensibles sans rapport avec la demande lorsqu’elles ne sont pas nécessaires.",
    privacyH4:"4. Informations de paiement", privacyP4:"Les paiements sont actuellement effectués via Zelle. We Translate n’a pas besoin de votre mot de passe bancaire en ligne ni de vos identifiants et ne vous demandera jamais de les fournir sur ce site.",
    privacyH5:"5. Prestataires de services", privacyP5:"Des prestataires d’hébergement, de messagerie, de stockage de fichiers ou de traitement de formulaires peuvent traiter des informations pour notre compte lorsque cela est nécessaire au fonctionnement du site et à la prestation des services. Les prestataires exacts peuvent évoluer au fur et à mesure de la finalisation du système.",
    privacyH6:"6. Conservation", privacyP6:"Les documents et informations de demande ne doivent être conservés que pendant la durée raisonnablement nécessaire pour terminer la traduction, gérer les révisions ou litiges, conserver les dossiers commerciaux requis et respecter les obligations légales. Les durées peuvent varier selon la demande.",
    privacyH7:"7. Sécurité", privacyP7:"Des mesures techniques et organisationnelles raisonnables doivent être utilisées pour protéger les documents soumis. Aucun système de transmission ou de stockage en ligne ne peut être garanti comme totalement sécurisé.",
    privacyH8:"8. Partage", privacyP8:"We Translate ne vend pas les documents clients ni les informations personnelles. Les informations peuvent être partagées avec des prestataires qui contribuent au fonctionnement du service, lorsque la loi l’exige, ou lorsque cela est nécessaire pour protéger des droits légaux et prévenir la fraude ou les abus.",
    privacyH9:"9. Vos choix", privacyP9:"Vous pouvez contacter We Translate pour poser des questions sur les informations associées à votre demande ou demander leur suppression lorsque cela est légalement et opérationnellement possible.",
    privacyH10:"10. Mineurs", privacyP10:"Ce service n’est pas conçu pour que des enfants soumettent des documents de façon indépendante. Un parent, tuteur ou adulte autorisé doit gérer les demandes impliquant les documents d’un mineur.",
    privacyH11:"11. Mises à jour de la politique", privacyP11:"Cette politique peut être mise à jour au fur et à mesure que le site, l’hébergement, le système d’envoi ou les processus de l’entreprise évoluent. La date d’entrée en vigueur sera mise à jour en cas de changement important.",
    privacyH12:"12. Contact", privacyP12:"Les questions de confidentialité peuvent être envoyées via le processus de devis/contact du site. Une adresse e-mail dédiée pourra être ajoutée une fois confirmée.",
    refundsTitle:"Remboursements et annulations",
    refundH1:"Avant le paiement", refundP1:"Vous pouvez refuser un devis à tout moment avant le paiement et avant le début du travail de traduction. La simple demande de devis est gratuite, sauf si un service payant distinct a été expressément accepté à l’avance.",
    refundH2:"Après paiement mais avant le début du travail", refundP2:"Si vous annulez avant le début du travail de traduction, le paiement peut généralement être remboursé, déduction faite des frais de transfert ou de transaction non remboursables réellement applicables.",
    refundH3:"Après le début du travail", refundP3:"Si le travail de traduction a déjà commencé, un remboursement intégral peut ne pas être disponible. Tout remboursement dépendra de la partie du travail déjà effectuée et des frais déjà engagés.",
    refundH4:"Après livraison", refundP4:"Une fois la traduction terminée livrée, les paiements sont généralement non remboursables. Si vous pensez qu’il existe une erreur de traduction, contactez-nous rapidement en indiquant le problème précis afin qu’il puisse être examiné et, si nécessaire, corrigé.",
    refundH5:"Modifications demandées par le client", refundP5:"Si vous modifiez le document source, la langue cible, la mise en page, le délai ou l’étendue du travail après avoir approuvé le devis, des frais supplémentaires peuvent s’appliquer. Des changements importants peuvent nécessiter un nouveau devis.",
    refundH6:"Refus par une institution", refundP6:"Un remboursement n’est pas automatiquement dû parce qu’un tiers, une agence, une école, un employeur, un tribunal ou un organisme public refuse une traduction, notamment lorsque des exigences particulières de certification, de notarisation ou de mise en page n’ont pas été indiquées et confirmées avant le début du travail.",
    refundH7:"Paiements en double ou erronés", refundP7:"Si vous pensez avoir effectué un paiement Zelle en double ou incorrect, contactez We Translate dès que possible avec les détails du paiement afin que la situation puisse être examinée.",
    refundH8:"Comment demander une annulation ou un remboursement", refundP8:"Utilisez le processus de contact/devis du site et indiquez l’adresse e-mail utilisée pour la commande, la référence du document ou de la demande si disponible, ainsi que la raison de la demande. Une adresse e-mail professionnelle dédiée pourra être ajoutée une fois confirmée.",
    metaHomeTitle:"We Translate — Traduction de documents", metaHomeDesc:"Traduction professionnelle de documents en anglais, espagnol, français et créole haïtien.",
    metaServicesTitle:"Services — We Translate", metaServicesDesc:"Services de traduction pour documents officiels et non officiels.",
    metaProcessTitle:"Fonctionnement — We Translate", metaProcessDesc:"Découvrez comment fonctionne le processus de traduction de documents We Translate.",
    metaPricingTitle:"Tarifs — We Translate", metaPricingDesc:"Tarifs et informations sur les devis We Translate.",
    metaQuoteTitle:"Obtenir un devis — We Translate", metaQuoteDesc:"Envoyez un document et demandez un devis de traduction.",
    metaFaqTitle:"FAQ — We Translate", metaFaqDesc:"Questions fréquentes sur We Translate.",
    metaTermsTitle:"Conditions générales — We Translate", metaTermsDesc:"Conditions générales des services de traduction de documents We Translate.",
    metaPrivacyTitle:"Politique de confidentialité — We Translate", metaPrivacyDesc:"Politique de confidentialité pour les demandes de traduction We Translate.",
    metaRefundsTitle:"Remboursements et annulations — We Translate", metaRefundsDesc:"Politique de remboursement et d’annulation des services We Translate.",
    sameLang:"Veuillez choisir deux langues différentes.", requestReady:"Demande préparée. Votre document est sélectionné. Connectez l’e-mail professionnel ou un formulaire sécurisé avant le lancement afin que la demande puisse être envoyée."
  },
  es: {
    top:"Traducción de documentos • Entrega habitual en 24–48 horas",
    range:"Los presupuestos suelen estar entre $25 y $50 por documento",
    serv:"Servicios", how:"Cómo funciona", pricing:"Precios", quote:"Pedir presupuesto",
    ey:"Traducción profesional de documentos",
    title:"Tus palabras,<br><em>bien entendidas.</em>",
    hero:"Envíanos tu documento y dinos a qué idioma debe traducirse. Traducimos entre inglés, español, francés y criollo haitiano y entregamos el archivo final por correo electrónico.",
    upload:"Subir documento", see:"Ver cómo funciona", langs:"Idiomas", turn:"Tiempo habitual", range2:"Rango habitual", emailWord:"Correo", delivery:"Entrega digital",
    langEnglish:"Inglés", langSpanish:"Español", langFrench:"Francés", langCreole:"Criollo haitiano",
    explore:"Explorar", exploreTitle:"Todo lo que necesitas, sin ponerlo todo en una sola página.",
    homeServices:"Servicios", homeServicesP:"Consulta los tipos de documentos oficiales y no oficiales que traducimos.",
    homeHow:"Cómo funciona", homeHowP:"Sube el archivo, recibe el presupuesto, paga y recibe la traducción final.",
    homePricing:"Precios", homePricingP:"Conoce el rango habitual de $25–$50 y qué puede afectar tu presupuesto.",
    homeQuote:"Pedir presupuesto", homeQuoteP:"Elige los idiomas y sube el documento que quieres que revisemos.",
    homeFaq:"Preguntas frecuentes", homeFaqP:"Plazos, documentos oficiales, pagos y preguntas comunes.",
    homeStart:"Empezar ahora", homeStartP:"¿Listo para traducir? Envíanos el documento y primero lo revisaremos.",
    what:"Qué traducimos", serviceHero:"Documentos importantes, traducidos con claridad.", serviceHeroP:"Trabajamos con documentos oficiales y no oficiales en inglés, español, francés y criollo haitiano.",
    c1:"Documentos civiles", c1p:"Actas de nacimiento y matrimonio, registros de identidad y otros documentos personales.",
    c2:"Escuela y estudios", c2p:"Expedientes, diplomas, cartas, registros de matrícula y documentos académicos.",
    c3:"Trabajo y negocios", c3p:"Cartas laborales, documentos comerciales, formularios, políticas y correspondencia.",
    c4:"Documentos personales", c4p:"Cartas, declaraciones, avisos y otros documentos no oficiales.",
    c5:"Formularios y registros", c5p:"Formularios administrativos, registros y documentos de respaldo.",
    c6:"¿Algo más?", c6p:"Súbelo. Primero revisaremos el archivo para confirmar si podemos aceptar el proyecto.",
    simple:"Simple de principio a fin", simple2:"Envía el archivo. Aprueba el presupuesto. Recibe la traducción.", processIntro:"Sin configuraciones de cuenta complicadas. Empieza con tu documento y nosotros te guiamos en el resto.",
    p1:"Subir", p1p:"Elige el idioma de origen y destino y envía el documento.",
    p2:"Revisión y presupuesto", p2p:"Revisamos la extensión y complejidad y enviamos el precio exacto antes de comenzar.",
    p3:"Pagar", p3p:"Por ahora, el pago se realiza por Zelle. Los detalles se confirman con tu presupuesto.",
    p4:"Recibir", p4p:"La traducción terminada se envía al correo electrónico que proporcionaste.",
    clear:"Precios claros", clear2:"Primero un rango claro. Después, un presupuesto exacto tras revisar el documento.", pricingIntro:"La mayoría de los documentos estándar se encuentran dentro del rango indicado. Confirmamos el monto exacto antes de empezar cualquier trabajo.",
    per:"rango habitual por documento", pc1:"El precio final depende de la extensión, el formato, la combinación de idiomas y la complejidad.", pc2:"Apruebas el presupuesto antes de que comience la traducción.", pc3:"Los documentos largos, de varias páginas o especializados pueden cotizarse fuera del rango habitual.",
    paymentLabel:"Pago", zelleAccepted:"Por ahora aceptamos Zelle.", zn:"No envíes el pago hasta que confirmemos tu presupuesto.",
    rq:"Solicitar presupuesto", rq2:"Cuéntanos qué necesitas traducir.", rqp:"Completa el formulario y selecciona tu documento. Revisaremos tu solicitud antes de confirmar el precio final.", z:"Pago por Zelle",
    email:"Tu correo", emailPh:"tu@ejemplo.com", from:"Traducir de", to:"Traducir a", selectLang:"Seleccionar idioma", doc:"Tu documento", choose:"Elegir documento", notes:"¿Algo que debamos saber? (opcional)", notesPh:"Fecha límite, formato, número de páginas, etc.", privacy:"Envía solo documentos que tengas permiso para compartir. Tu archivo debe utilizarse únicamente para preparar y completar tu solicitud de traducción.", agreeHtml:'Acepto los <a href="terms.html" target="_blank">Términos y condiciones</a> y la <a href="privacy.html" target="_blank">Política de privacidad</a>.', prepare:"Preparar solicitud",
    faq:"Algunas cosas que debes saber antes de enviar tu documento.", q1:"¿Cuánto tarda una traducción?", a1:"La mayoría de las solicitudes estándar tienen como objetivo 24–48 horas después de confirmar el presupuesto y el pago. Los archivos más grandes o complejos pueden tardar más.", q2:"¿Cuánto costará?", a2:"La mayoría de los documentos estándar están entre $25 y $50. Confirmamos el precio exacto después de revisar el archivo.", q3:"¿Qué idiomas ofrecen?", a3:"Inglés, español, francés y criollo haitiano.", q4:"¿Aceptan documentos oficiales?", a4:"Sí, puedes enviar documentos oficiales o no oficiales para revisión. Si la institución receptora exige una certificación, notarización, credencial específica del traductor o formato particular, indícanoslo antes de empezar para poder confirmar el requisito.", q5:"¿Cómo pago?", a5:"Actualmente aceptamos Zelle. Espera a que se confirme tu presupuesto final antes de enviar el pago.",
    termsLink:"Términos y condiciones", privacyLink:"Política de privacidad", refundLink:"Reembolsos y cancelaciones", faqLink:"Preguntas frecuentes", foot:"Palabras claras. Entre idiomas.", fl:"Inglés • Español • Francés • Criollo haitiano",
    legalLabel:"Legal", effective:"Vigente desde: 22 de septiembre de 2026", termsTitle:"Términos y condiciones",
    termsIntro:"Estos términos explican cómo se gestionan las solicitudes de presupuesto, los pagos, el trabajo de traducción y la entrega. Al enviar una solicitud o aprobar un presupuesto, aceptas estos términos.",
    termsH1:"1. Servicios", termsP1:"We Translate presta servicios de traducción de documentos entre inglés, español, francés y criollo haitiano. Podemos aceptar o rechazar una solicitud después de revisar el documento, la combinación de idiomas, los requisitos de formato, la fecha límite y la complejidad.",
    termsH2:"2. Presupuestos y precios", termsP2:"Los precios mostrados en el sitio son solo estimaciones. Se espera que la mayoría de los documentos estándar estén dentro del rango indicado de $25–$50, pero el precio final puede ser mayor o menor según la extensión, complejidad, formato y requisitos especiales. El trabajo de traducción comienza únicamente después de que el cliente aprueba el presupuesto final y se recibe cualquier pago requerido.",
    termsH3:"3. Plazos", termsP3:"El plazo habitual mostrado en el sitio es de 24–48 horas para solicitudes estándar después de aprobar el presupuesto y realizar el pago. Es una estimación, no una garantía. Los archivos grandes, escaneos de baja calidad, temas especializados o revisiones pueden requerir más tiempo.",
    termsH4:"4. Responsabilidades del cliente", termsP4:"Eres responsable de enviar archivos completos y legibles, proporcionar instrucciones correctas y confirmar el idioma de destino y el uso previsto. Debes tener el derecho legal o permiso para compartir cada documento que envíes.",
    termsH5:"5. Documentos oficiales y aceptación", termsP5:"We Translate puede traducir documentos oficiales y no oficiales. Salvo que se confirme específicamente por escrito para un pedido determinado, no garantizamos que una traducción cumpla requisitos de certificación, notarización, uso judicial, trámites migratorios, universidades, organismos gubernamentales u otra institución receptora. El cliente debe confirmar los requisitos de la institución antes de realizar el pedido.",
    termsH6:"6. Pagos", termsP6:"Actualmente los pagos se aceptan por Zelle después de confirmar el presupuesto final. No envíes el pago antes de recibir esa confirmación. Los datos de pago pueden actualizarse.",
    termsH7:"7. Revisiones", termsP7:"Si crees que una traducción entregada contiene un error, contáctanos pronto indicando la sección específica. Las correcciones razonables de errores de traducción pueden realizarse sin cargo adicional. Los cambios en el documento original, contenido nuevo, nuevas solicitudes de formato o cambios de instrucciones pueden requerir un nuevo presupuesto.",
    termsH8:"8. Cancelaciones y reembolsos", termsP8:'La elegibilidad para cancelación o reembolso depende de cuánto trabajo se haya completado. Consulta nuestra <a href="refunds.html">Política de reembolsos y cancelaciones</a> para más información.',
    termsH9:"9. Entrega de archivos", termsP9:"Las traducciones terminadas normalmente se entregan electrónicamente al correo proporcionado por el cliente. El cliente es responsable de proporcionar una dirección válida y revisar las carpetas de spam o correo no deseado.",
    termsH10:"10. Exactitud y limitaciones", termsP10:"Nuestro objetivo es ofrecer traducciones cuidadosas y precisas. Sin embargo, el cliente es responsable de revisar nombres, fechas, números y otros datos críticos al recibir el trabajo. En la medida permitida por la ley, We Translate no responde por pérdidas indirectas o consecuentes derivadas del uso de una traducción o de la decisión de una institución de rechazarla.",
    termsH11:"11. Envíos prohibidos", termsP11:"No puedes enviar contenido que no tengas permiso para compartir, contenido ilegal, malware o archivos destinados a facilitar fraude, suplantación u otra actividad ilegal.",
    termsH12:"12. Cambios en estos términos", termsP12:"Podemos actualizar estos términos a medida que el servicio evolucione. La fecha de vigencia indicada arriba se actualizará cuando haya cambios importantes.",
    termsH13:"13. Contacto", termsP13:"Las preguntas sobre estos términos pueden enviarse mediante el proceso de presupuesto/contacto del sitio. Se podrá añadir un correo empresarial específico cuando esté confirmado.",
    privacyTitle:"Política de privacidad", privacyIntro:"Las solicitudes de traducción pueden contener información personal sensible. Esta política explica qué información interviene en el servicio y cómo debe manejarse.",
    privacyH1:"1. Información que proporcionas", privacyP1:"Al solicitar un presupuesto o una traducción, puedes proporcionar tu correo electrónico, los idiomas de origen y destino, notas y los documentos que decidas subir. Los documentos enviados pueden contener información personal tuya o de otras personas.",
    privacyH2:"2. Cómo usamos la información", privacyP2:"La información enviada a través del sitio se utiliza para revisar tu solicitud, preparar un presupuesto, realizar la traducción, comunicarnos contigo, entregar el trabajo terminado, gestionar solicitudes relacionadas de atención al cliente y mantener los registros empresariales necesarios.",
    privacyH3:"3. Documentos e información sensible", privacyP3:"Envía solo los documentos necesarios para la traducción y que tengas permiso para compartir. Evita incluir información sensible no relacionada cuando no sea necesaria.",
    privacyH4:"4. Información de pago", privacyP4:"Actualmente los pagos se realizan mediante Zelle. We Translate no necesita tu contraseña bancaria ni tus credenciales de acceso y nunca te pedirá que las proporciones a través de este sitio.",
    privacyH5:"5. Proveedores de servicios", privacyP5:"Los proveedores de alojamiento, correo electrónico, almacenamiento de archivos o procesamiento de formularios pueden tratar información en nuestro nombre cuando sea necesario para operar el sitio y prestar los servicios de traducción. Los proveedores exactos pueden cambiar a medida que se finaliza el sistema.",
    privacyH6:"6. Conservación", privacyP6:"Los documentos y la información de la solicitud deben conservarse solo durante el tiempo razonablemente necesario para completar la traducción, gestionar revisiones o disputas, mantener los registros empresariales requeridos y cumplir obligaciones legales. Los periodos pueden variar según la solicitud.",
    privacyH7:"7. Seguridad", privacyP7:"Deben utilizarse medidas técnicas y organizativas razonables para proteger los documentos enviados. Ningún sistema de transmisión o almacenamiento en línea puede garantizarse como completamente seguro.",
    privacyH8:"8. Compartir información", privacyP8:"We Translate no vende documentos de clientes ni información personal. La información puede compartirse con proveedores que ayudan a operar el servicio, cuando la ley lo exija o cuando sea necesario para proteger derechos legales y prevenir fraude o uso indebido.",
    privacyH9:"9. Tus opciones", privacyP9:"Puedes contactar a We Translate para hacer preguntas sobre la información asociada a tu solicitud o pedir su eliminación cuando sea legal y operativamente posible.",
    privacyH10:"10. Menores", privacyP10:"Este servicio no está diseñado para que los menores envíen documentos de forma independiente. Un padre, tutor o adulto autorizado debe gestionar las solicitudes relacionadas con documentos de un menor.",
    privacyH11:"11. Actualizaciones de la política", privacyP11:"Esta política puede actualizarse a medida que cambien el sitio, el alojamiento, el sistema de carga o los procesos del negocio. La fecha de vigencia se actualizará cuando haya cambios importantes.",
    privacyH12:"12. Contacto", privacyP12:"Las preguntas sobre privacidad pueden enviarse mediante el proceso de presupuesto/contacto del sitio. Se podrá añadir un correo específico de privacidad o del negocio una vez confirmado.",
    refundsTitle:"Reembolsos y cancelaciones",
    refundH1:"Antes del pago", refundP1:"Puedes rechazar un presupuesto en cualquier momento antes del pago y antes de que comience el trabajo de traducción. No hay ningún cargo por solicitar un presupuesto, salvo que se acuerde expresamente por adelantado un servicio de pago separado.",
    refundH2:"Después del pago pero antes de empezar", refundP2:"Si cancelas antes de que haya comenzado el trabajo de traducción, el pago normalmente podrá reembolsarse, menos cualquier coste real no reembolsable de transferencia o transacción.",
    refundH3:"Después de empezar el trabajo", refundP3:"Si el trabajo de traducción ya ha comenzado, es posible que no haya un reembolso completo. Cualquier reembolso dependerá de la parte del trabajo ya realizada y de los costes ya incurridos.",
    refundH4:"Después de la entrega", refundP4:"Una vez entregada la traducción terminada, los pagos generalmente no son reembolsables. Si crees que existe un error de traducción, contáctanos pronto con el problema específico para que pueda revisarse y, cuando corresponda, corregirse.",
    refundH5:"Cambios del cliente", refundP5:"Si cambias el documento de origen, el idioma de destino, el formato, la fecha límite o el alcance después de aprobar el presupuesto, pueden aplicarse cargos adicionales. Los cambios importantes pueden requerir un nuevo presupuesto.",
    refundH6:"Rechazo por una institución", refundP6:"No corresponde automáticamente un reembolso porque un tercero, agencia, escuela, empleador, tribunal u organismo gubernamental rechace una traducción, especialmente cuando requisitos especiales de certificación, notarización o formato no fueron informados y confirmados antes de comenzar el trabajo.",
    refundH7:"Pagos duplicados o equivocados", refundP7:"Si crees que realizaste un pago Zelle duplicado o incorrecto, contacta a We Translate lo antes posible con los detalles del pago para que podamos revisarlo.",
    refundH8:"Cómo solicitar una cancelación o reembolso", refundP8:"Utiliza el proceso de contacto/presupuesto del sitio e incluye el correo usado para el pedido, la referencia del documento o solicitud si está disponible y el motivo de la solicitud. Se podrá añadir un correo empresarial específico una vez confirmado.",
    metaHomeTitle:"We Translate — Traducción de documentos", metaHomeDesc:"Traducción profesional de documentos en inglés, español, francés y criollo haitiano.",
    metaServicesTitle:"Servicios — We Translate", metaServicesDesc:"Servicios de traducción para documentos oficiales y no oficiales.",
    metaProcessTitle:"Cómo funciona — We Translate", metaProcessDesc:"Cómo funciona el proceso de traducción de documentos de We Translate.",
    metaPricingTitle:"Precios — We Translate", metaPricingDesc:"Precios e información sobre presupuestos de We Translate.",
    metaQuoteTitle:"Pedir presupuesto — We Translate", metaQuoteDesc:"Sube un documento y solicita un presupuesto de traducción.",
    metaFaqTitle:"Preguntas frecuentes — We Translate", metaFaqDesc:"Preguntas frecuentes sobre We Translate.",
    metaTermsTitle:"Términos y condiciones — We Translate", metaTermsDesc:"Términos y condiciones de los servicios de traducción de documentos de We Translate.",
    metaPrivacyTitle:"Política de privacidad — We Translate", metaPrivacyDesc:"Política de privacidad para solicitudes de traducción de We Translate.",
    metaRefundsTitle:"Reembolsos y cancelaciones — We Translate", metaRefundsDesc:"Política de reembolsos y cancelaciones de los servicios de We Translate.",
    sameLang:"Elige dos idiomas diferentes.", requestReady:"Solicitud preparada. Tu documento está seleccionado. Conecta el correo empresarial o un formulario seguro antes del lanzamiento para que la solicitud pueda enviarse."
  },
  ht: {
    top:"Tradiksyon dokiman • Delè nòmal 24–48 èdtan",
    range:"Pri yo anjeneral ant $25 ak $50 pou chak dokiman",
    serv:"Sèvis", how:"Kijan sa mache", pricing:"Pri", quote:"Mande yon pri",
    ey:"Tradiksyon pwofesyonèl pou dokiman",
    title:"Pawòl ou yo,<br><em>byen konprann.</em>",
    hero:"Voye dokiman ou a epi di nou nan ki lang ou bezwen li. Nou tradui ant Anglè, Panyòl, Fransè ak Kreyòl Ayisyen, epi nou voye fichye final la ba ou pa imèl.",
    upload:"Voye dokiman an", see:"Gade kijan sa mache", langs:"Lang", turn:"Delè nòmal", range2:"Ranje pri nòmal", emailWord:"Imèl", delivery:"Livrezon dijital",
    langEnglish:"Anglè", langSpanish:"Panyòl", langFrench:"Fransè", langCreole:"Kreyòl Ayisyen",
    explore:"Dekouvri", exploreTitle:"Tout sa ou bezwen, san nou pa mete tout bagay sou yon sèl paj.",
    homeServices:"Sèvis", homeServicesP:"Gade kalite dokiman ofisyèl ak dokiman ki pa ofisyèl nou tradui.",
    homeHow:"Kijan sa mache", homeHowP:"Voye fichye a, resevwa pri a, peye epi resevwa tradiksyon final la.",
    homePricing:"Pri", homePricingP:"Konprann ranje pri nòmal $25–$50 la ak sa ki ka chanje pri ou.",
    homeQuote:"Mande yon pri", homeQuoteP:"Chwazi lang yo epi voye dokiman ou vle nou revize a.",
    homeFaq:"Kesyon moun poze souvan", homeFaqP:"Delè, dokiman ofisyèl, peman ak kesyon ki pi komen yo.",
    homeStart:"Kòmanse kounye a", homeStartP:"Pare pou tradui? Voye dokiman an epi n ap revize li anvan.",
    what:"Sa nou tradui", serviceHero:"Dokiman ki enpòtan, tradui ak anpil klate.", serviceHeroP:"Nou travay ak dokiman ofisyèl ak dokiman ki pa ofisyèl an Anglè, Panyòl, Fransè ak Kreyòl Ayisyen.",
    c1:"Dokiman sivil", c1p:"Ak nesans, ak maryaj, pyès idantite ak lòt dokiman pèsonèl.",
    c2:"Lekòl ak etid", c2p:"Relve nòt, diplòm, lèt, prèv enskripsyon ak lòt dokiman lekòl.",
    c3:"Travay ak biznis", c3p:"Lèt travay, dokiman biznis, fòm, règleman ak korespondans.",
    c4:"Dokiman pèsonèl", c4p:"Lèt, deklarasyon, avi ak lòt dokiman ki pa ofisyèl.",
    c5:"Fòm ak dosye", c5p:"Fòm administratif, dosye ak papye sipò.",
    c6:"Yon lòt bagay?", c6p:"Voye li. N ap gade fichye a anvan pou konfime si nou ka pran pwojè a.",
    simple:"Senp depi nan kòmansman rive nan fen", simple2:"Voye fichye a. Apwouve pri a. Resevwa tradiksyon an.", processIntro:"Pa gen bezwen pou kreye yon kont konplike. Kòmanse ak dokiman ou epi n ap gide w pou rès la.",
    p1:"Voye", p1p:"Chwazi lang dokiman an ak lang ou bezwen an, epi voye dokiman an.",
    p2:"Revizyon ak pri", p2p:"Nou gade longè ak konpleksite dokiman an epi nou voye pri egzak la anvan travay la kòmanse.",
    p3:"Peye", p3p:"Pou kounye a, peman fèt pa Zelle. Nou konfime detay yo ansanm ak pri ou.",
    p4:"Resevwa", p4p:"Nou voye tradiksyon fini an nan adrès imèl ou te bay la.",
    clear:"Pri ki senp", clear2:"Yon ranje pri klè anvan. Yon pri egzak apre nou wè dokiman an.", pricingIntro:"Pifò dokiman nòmal tonbe nan ranje pri ki anba a. Nou konfime kantite egzak la anvan travay la kòmanse.",
    per:"ranje pri nòmal pou chak dokiman", pc1:"Pri final la depann de longè dokiman an, fòma li, lang yo ak nivo konpleksite a.", pc2:"Ou apwouve pri a anvan tradiksyon an kòmanse.", pc3:"Gwo dokiman, dokiman ki gen plizyè paj oswa dokiman espesyalize ka depase ranje pri nòmal la.",
    paymentLabel:"Peman", zelleAccepted:"Pou kounye a nou aksepte Zelle.", zn:"Pa voye peman an anvan nou konfime pri ou.",
    rq:"Mande yon pri", rq2:"Di nou sa ou bezwen tradui.", rqp:"Ranpli fòm nan epi chwazi dokiman ou. N ap revize demann lan anvan nou konfime pri final la.", z:"Peman Zelle",
    email:"Imèl ou", emailPh:"ou@egzanp.com", from:"Tradui soti nan", to:"Tradui pou ale nan", selectLang:"Chwazi yon lang", doc:"Dokiman ou", choose:"Chwazi yon dokiman", notes:"Gen yon bagay nou dwe konnen? (opsyonèl)", notesPh:"Dat limit, fòma ou bezwen, kantite paj, elatriye.", privacy:"Voye sèlman dokiman ou gen pèmisyon pou pataje. Fichye ou a dwe itilize sèlman pou prepare epi konplete demann tradiksyon ou.", agreeHtml:'Mwen dakò ak <a href="terms.html" target="_blank">Tèm ak Kondisyon yo</a> ak <a href="privacy.html" target="_blank">Règleman sou Konfidansyalite a</a>.', prepare:"Prepare demann pri a",
    faq:"Kèk bagay pou konnen anvan ou voye dokiman ou.", q1:"Konbyen tan yon tradiksyon pran?", a1:"Pou pifò demann nòmal, objektif la se 24–48 èdtan apre pri ak peman an konfime. Gwo fichye oswa fichye ki pi konplike ka pran plis tan.", q2:"Konbyen sa ap koute?", a2:"Pifò dokiman nòmal tonbe ant $25 ak $50. Nou konfime pri egzak la apre nou fin gade fichye a.", q3:"Ki lang nou sipòte?", a3:"Anglè, Panyòl, Fransè ak Kreyòl Ayisyen.", q4:"Èske nou aksepte dokiman ofisyèl?", a4:"Wi, ou ka voye dokiman ofisyèl oswa dokiman ki pa ofisyèl pou nou revize. Si enstitisyon ki pral resevwa dokiman an mande yon sètifikasyon, notè, yon kalifikasyon espesifik pou tradiktè a oswa yon fòma presi, di nou sa anvan travay la kòmanse pou nou ka konfime kondisyon an.", q5:"Kijan pou peye?", a5:"Kounye a nou aksepte Zelle. Tann nou konfime pri final la anvan ou voye peman an.",
    termsLink:"Tèm ak Kondisyon", privacyLink:"Règleman sou Konfidansyalite", refundLink:"Ranbousman ak Anilasyon", faqLink:"Kesyon souvan", foot:"Mo klè. Nan plizyè lang.", fl:"Anglè • Panyòl • Fransè • Kreyòl Ayisyen",
    legalLabel:"Legal", effective:"An vigè depi: 22 septanm 2026", termsTitle:"Tèm ak Kondisyon",
    termsIntro:"Tèm sa yo esplike kijan nou jere demann pri, peman, travay tradiksyon ak livrezon. Lè ou voye yon demann oswa ou apwouve yon pri, sa vle di ou dakò ak tèm sa yo.",
    termsH1:"1. Sèvis", termsP1:"We Translate bay sèvis tradiksyon dokiman ant Anglè, Panyòl, Fransè ak Kreyòl Ayisyen. Nou ka aksepte oswa refize yon demann apre nou fin revize dokiman an, lang yo, kondisyon fòma yo, dat limit la ak nivo konpleksite a.",
    termsH2:"2. Pri ak estimasyon", termsP2:"Pri ki sou sit la se estimasyon sèlman. Pifò dokiman nòmal ta dwe tonbe nan ranje $25–$50 la, men pri final la ka pi wo oswa pi ba selon longè, konpleksite, fòma ak kondisyon espesyal. Travay tradiksyon an kòmanse sèlman apre kliyan an apwouve pri final la epi nou resevwa peman ki nesesè a.",
    termsH3:"3. Delè", termsP3:"Delè nòmal ki sou sit la se 24–48 èdtan pou demann nòmal apre pri ak peman an konfime. Sa se yon estimasyon, li pa yon garanti. Gwo fichye, move kalite eskane, sijè espesyalize oswa revizyon ka pran plis tan.",
    termsH4:"4. Responsablite kliyan an", termsP4:"Se responsablite ou pou voye fichye ki konplè ak lizib, bay enstriksyon ki egzak, epi konfime lang ou bezwen an ak kijan dokiman an pral sèvi. Ou dwe gen dwa legal oswa pèmisyon pou pataje chak dokiman ou voye.",
    termsH5:"5. Dokiman ofisyèl ak akseptasyon", termsP5:"We Translate ka tradui dokiman ofisyèl ak dokiman ki pa ofisyèl. Sòf si nou konfime sa alekri pou yon lòd espesifik, nou pa garanti yon tradiksyon ap satisfè kondisyon pou sètifikasyon, notè, itilizasyon nan tribinal, dosye imigrasyon, inivèsite, ajans gouvènman oswa nenpòt lòt enstitisyon. Kliyan an dwe verifye kondisyon enstitisyon an anvan li pase lòd.",
    termsH6:"6. Peman", termsP6:"Kounye a nou aksepte peman pa Zelle apre pri final la konfime. Pa voye peman an anvan ou resevwa konfimasyon pri a. Detay peman yo ka chanje pita.",
    termsH7:"7. Koreksyon", termsP7:"Si ou panse yon tradiksyon nou livre gen yon erè, kontakte nou rapidman epi montre nou pati ki konsène a. Koreksyon rezonab pou erè tradiksyon ka fèt san lòt frè. Chanjman nan dokiman orijinal la, nouvo kontni, nouvo demann fòma oswa chanjman enstriksyon ka mande yon nouvo pri.",
    termsH8:"8. Anilasyon ak ranbousman", termsP8:'Elijibilite pou anilasyon oswa ranbousman depann de kantite travay ki deja fèt. Gade <a href="refunds.html">Règleman Ranbousman ak Anilasyon</a> nou an pou plis detay.',
    termsH9:"9. Livrezon fichye", termsP9:"Anjeneral nou voye tradiksyon fini yo elektwonikman nan adrès imèl kliyan an bay la. Se responsablite kliyan an pou bay yon adrès imèl ki valab epi verifye spam oswa junk.",
    termsH10:"10. Presizyon ak limit", termsP10:"Nou vize bay tradiksyon ki fèt ak anpil swen ak presizyon. Men kliyan an dwe verifye non, dat, chif ak lòt detay enpòtan lè li resevwa travay la. Nan limit lalwa pèmèt, We Translate pa responsab pou pèt endirèk oswa konsekans ki soti nan itilizasyon yon tradiksyon oswa desizyon yon enstitisyon pou refize li.",
    termsH11:"11. Bagay ou pa gen dwa voye", termsP11:"Ou pa dwe voye kontni ou pa gen pèmisyon pou pataje, kontni ilegal, lojisyèl malveyan, oswa fichye ki fèt pou ede fwod, pran idantite yon lòt moun oswa nenpòt lòt aktivite ilegal.",
    termsH12:"12. Chanjman nan tèm sa yo", termsP12:"Nou ka mete tèm sa yo ajou pandan sèvis la ap evolye. Dat ki anlè a ap chanje lè gen gwo chanjman.",
    termsH13:"13. Kontakte nou", termsP13:"Kesyon sou tèm sa yo ka voye atravè pwosesis pri/kontak sou sit la. Nou ka ajoute yon imèl biznis dedye lè li konfime.",
    privacyTitle:"Règleman sou Konfidansyalite", privacyIntro:"Demann tradiksyon ka gen enfòmasyon pèsonèl ki sansib. Règleman sa a esplike ki enfòmasyon ki enplike nan sèvis la ak kijan yo dwe jere yo.",
    privacyH1:"1. Enfòmasyon ou bay", privacyP1:"Lè w mande yon pri oswa yon tradiksyon, ou ka bay adrès imèl ou, lang sous ak lang sib, nòt, ak dokiman ou chwazi voye. Dokiman yo ka gen enfòmasyon pèsonèl sou ou oswa sou lòt moun.",
    privacyH2:"2. Kijan nou itilize enfòmasyon yo", privacyP2:"Enfòmasyon ou voye sou sit la sèvi pou revize demann ou, prepare yon pri, fè tradiksyon an, kominike avèk ou, livre travay fini an, jere kestyon sèvis kliyan ki gen rapò epi kenbe dosye biznis ki nesesè.",
    privacyH3:"3. Dokiman ak enfòmasyon sansib", privacyP3:"Voye sèlman dokiman ki nesesè pou tradiksyon an epi ou gen pèmisyon pou pataje. Pa mete lòt enfòmasyon sansib ki pa nesesè pou sèvis la.",
    privacyH4:"4. Enfòmasyon sou peman", privacyP4:"Kounye a peman fèt atravè Zelle. We Translate pa bezwen modpas bank ou sou entènèt ni enfòmasyon koneksyon ou epi nou pap janm mande w bay yo sou sit sa a.",
    privacyH5:"5. Founisè sèvis", privacyP5:"Founisè hosting, imèl, depo fichye oswa pwosesis fòm ka trete enfòmasyon pou nou lè sa nesesè pou fè sit la mache ak bay sèvis tradiksyon. Founisè egzak yo ka chanje pandan sistèm nan ap finalize.",
    privacyH6:"6. Konbyen tan nou kenbe enfòmasyon", privacyP6:"Dokiman ak enfòmasyon demann yo dwe rete sèlman pou kantite tan ki rezonab pou fini tradiksyon an, jere koreksyon oswa diskisyon, kenbe dosye biznis ki nesesè epi respekte obligasyon legal. Delè yo ka varye selon demann lan.",
    privacyH7:"7. Sekirite", privacyP7:"Nou dwe itilize mezi teknik ak òganizasyonèl ki rezonab pou pwoteje dokiman yo. Pa gen okenn sistèm transmisyon oswa depo sou entènèt ki ka garanti 100% sekirite.",
    privacyH8:"8. Pataje enfòmasyon", privacyP8:"We Translate pa vann dokiman kliyan oswa enfòmasyon pèsonèl. Enfòmasyon ka pataje ak founisè ki ede sèvis la mache, lè lalwa mande sa, oswa lè sa nesesè pou pwoteje dwa legal epi anpeche fwod oswa move itilizasyon.",
    privacyH9:"9. Chwa ou", privacyP9:"Ou ka kontakte We Translate pou poze kestyon sou enfòmasyon ki lye ak demann ou oswa mande pou efase yo lè sa posib selon lalwa ak operasyon sèvis la.",
    privacyH10:"10. Timoun", privacyP10:"Sèvis sa a pa fèt pou timoun voye dokiman poukont yo. Yon paran, gadyen oswa granmoun ki otorize dwe jere demann ki gen dokiman yon minè.",
    privacyH11:"11. Mizajou règleman an", privacyP11:"Nou ka mete règleman sa a ajou pandan sit la, hosting lan, sistèm upload la oswa pwosesis biznis yo ap chanje. Dat ki anlè a ap chanje lè gen gwo chanjman.",
    privacyH12:"12. Kontakte nou", privacyP12:"Kesyon sou konfidansyalite ka voye atravè pwosesis pri/kontak sou sit la. Nou ka ajoute yon imèl biznis oswa imèl konfidansyalite dedye lè li konfime.",
    refundsTitle:"Ranbousman ak Anilasyon",
    refundH1:"Anvan peman", refundP1:"Ou ka refize yon pri nenpòt lè anvan peman epi anvan travay tradiksyon an kòmanse. Pa gen frè sèlman paske ou mande yon pri, sòf si yo te dakò davans sou yon lòt sèvis peye.",
    refundH2:"Apre peman men anvan travay kòmanse", refundP2:"Si ou anile anvan travay tradiksyon an kòmanse, anjeneral peman an ka ranbouse, mwens nenpòt frè transfè oswa tranzaksyon ki vrèman pa ranbousab.",
    refundH3:"Apre travay la kòmanse", refundP3:"Si travay tradiksyon an deja kòmanse, yon ranbousman total ka pa disponib. Nenpòt ranbousman ap depann de pati travay la ki deja fèt ak depans ki deja fèt.",
    refundH4:"Apre livrezon", refundP4:"Lè tradiksyon fini an deja livre, anjeneral peman yo pa ranbousab. Si ou panse gen yon erè tradiksyon, kontakte nou rapidman ak pwoblèm presi a pou nou ka revize li epi korije li si sa nesesè.",
    refundH5:"Chanjman kliyan an", refundP5:"Si ou chanje dokiman sous la, lang sib la, fòma a, dat limit la oswa kantite travay la apre ou fin apwouve pri a, lòt frè ka aplike. Gwo chanjman ka mande yon nouvo pri.",
    refundH6:"Si yon enstitisyon refize tradiksyon an", refundP6:"Yon ranbousman pa otomatikman dwe fèt paske yon twazyèm pati, ajans, lekòl, patwon, tribinal oswa biwo gouvènman refize yon tradiksyon, espesyalman lè kondisyon espesyal pou sètifikasyon, notè oswa fòma pa t bay epi konfime anvan travay la kòmanse.",
    refundH7:"Peman doub oswa peman pa erè", refundP7:"Si ou panse ou fè yon peman Zelle doub oswa pa erè, kontakte We Translate pi vit posib ak detay peman an pou nou ka revize sa.",
    refundH8:"Kijan pou mande anilasyon oswa ranbousman", refundP8:"Itilize pwosesis kontak/pris sou sit la epi mete imèl ou te itilize pou lòd la, referans dokiman oswa demann lan si ou genyen li, ak rezon demann lan. Nou ka ajoute yon imèl biznis dedye lè li konfime.",
    metaHomeTitle:"We Translate — Tradiksyon Dokiman", metaHomeDesc:"Tradiksyon pwofesyonèl pou dokiman an Anglè, Panyòl, Fransè ak Kreyòl Ayisyen.",
    metaServicesTitle:"Sèvis — We Translate", metaServicesDesc:"Sèvis tradiksyon pou dokiman ofisyèl ak dokiman ki pa ofisyèl.",
    metaProcessTitle:"Kijan sa mache — We Translate", metaProcessDesc:"Kijan pwosesis tradiksyon dokiman We Translate la mache.",
    metaPricingTitle:"Pri — We Translate", metaPricingDesc:"Pri ak enfòmasyon sou demann pri We Translate.",
    metaQuoteTitle:"Mande yon pri — We Translate", metaQuoteDesc:"Voye yon dokiman epi mande yon pri pou tradiksyon.",
    metaFaqTitle:"Kesyon souvan — We Translate", metaFaqDesc:"Kesyon moun poze souvan sou We Translate.",
    metaTermsTitle:"Tèm ak Kondisyon — We Translate", metaTermsDesc:"Tèm ak kondisyon pou sèvis tradiksyon dokiman We Translate.",
    metaPrivacyTitle:"Règleman sou Konfidansyalite — We Translate", metaPrivacyDesc:"Règleman sou konfidansyalite pou demann tradiksyon We Translate.",
    metaRefundsTitle:"Ranbousman ak Anilasyon — We Translate", metaRefundsDesc:"Règleman ranbousman ak anilasyon pou sèvis We Translate.",
    sameLang:"Tanpri chwazi de lang diferan.", requestReady:"Demann lan pare. Dokiman ou chwazi a pare. Konekte imèl biznis la oswa yon fòm sekirize anvan lansman pou demann lan ka voye."
  }
};

const en={};
document.querySelectorAll("[data-t]").forEach(el=>{en[el.dataset.t]=el.textContent});
document.querySelectorAll("[data-h]").forEach(el=>{en[el.dataset.h]=el.innerHTML});
document.querySelectorAll("[data-ph]").forEach(el=>{en[el.dataset.ph]=el.getAttribute("placeholder")||""});
document.querySelectorAll("[data-content]").forEach(el=>{en[el.dataset.content]=el.getAttribute("content")||""});
dict.en=en;

function setLang(lang){
  const d=dict[lang]||dict.en;
  document.documentElement.lang=lang==="ht"?"ht":lang;
  document.querySelectorAll("[data-t]").forEach(el=>{const k=el.dataset.t;if(d[k]!==undefined)el.textContent=d[k]});
  document.querySelectorAll("[data-h]").forEach(el=>{const k=el.dataset.h;if(d[k]!==undefined)el.innerHTML=d[k]});
  document.querySelectorAll("[data-ph]").forEach(el=>{const k=el.dataset.ph;if(d[k]!==undefined)el.setAttribute("placeholder",d[k])});
  document.querySelectorAll("[data-content]").forEach(el=>{const k=el.dataset.content;if(d[k]!==undefined)el.setAttribute("content",d[k])});
  document.querySelectorAll(".langs button").forEach(b=>b.classList.toggle("on",b.dataset.lang===lang));
  localStorage.setItem("wt_lang",lang);
}

document.querySelectorAll(".langs button").forEach(b=>b.addEventListener("click",()=>setLang(b.dataset.lang)));
setLang(localStorage.getItem("wt_lang")||"en");

const yr=document.getElementById("yr"); if(yr) yr.textContent=new Date().getFullYear();

const file=document.getElementById("file");
if(file){file.addEventListener("change",()=>{const fn=document.getElementById("fn");if(fn)fn.textContent=file.files[0]?file.files[0].name:""});}

const form=document.getElementById("f");
if(form){
  form.addEventListener("submit",e=>{
    e.preventDefault();
    const lang=localStorage.getItem("wt_lang")||"en";
    const d=dict[lang]||dict.en;
    const a=document.getElementById("from").value;
    const b=document.getElementById("to").value;
    const n=document.getElementById("notice");
    n.style.display="block";
    if(a===b){n.textContent=d.sameLang||"Please choose two different languages.";return;}
    n.textContent=d.requestReady||"Request prepared.";
  });
}
